---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
index:
  category: "categories"
baseurl: "http://rickyrombo.github.io"
title: "rickyrombo"
taxonomies:
  artist: "artists"
  track: "tracks"
...
