---
contentdir: "content"
layoutdir: "layouts"
publishdir: "public"
index:
  category: "categories"
baseurl: "http://rickyrombo.com"
title: "rickyrombo"
taxonomies:
  artist: "artists"
  track: "tracks"
  series: "series"
...
